# Generated by Django 4.2 on 2024-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_content_alter_article_date_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ImageField(max_length=255, null=True, upload_to='articles', verbose_name='photo de couverture'),
        ),
    ]
