services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: blog-django-image
    volumes:
      - ./:/app:z
    env_file:
      - ./env/app.env
    depends_on:
      - db
    ports:
      - 8000:8000
    command: >
      bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  db:
    image: postgres:14.1-alpine
    restart: unless-stopped
    container_name: blog-db
    environment:
      - POSTGRES_DB=dbblog
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54320:5432'
    volumes: 
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:



