name: Build & Deploy
on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the blog
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{secrets.SSH_HOST}} 
          key: ${{secrets.SSH_KEY}} 
          username: ${{ secrets.SSH_USERNAME }} 
     
          script: |
            cd app 
            git pull origin prod
            docker compose -f docker-compose-prod.yaml down
            docker builder purne -f -a
            docker compose -f docker-compose-prod.yaml up --build -d 
